using System.Collections.Frozen;
using TomasAI.IFM.Domain.Trade.Order.Execution.Command.Extensions;
using TomasAI.IFM.Domain.Trade.Order.Execution.Command.State;
using TomasAI.IFM.Domain.Trade.Shared.Order.Execution;
using TomasAI.IFM.Shared.Domain;
using TomasAI.IFM.Shared.EventModelActor;
using TomasAI.IFM.Shared.EventModelActor.Contracts;
using TomasAI.IFM.Shared.EventSourcing;
using TomasAI.IFM.Shared.Validation;

namespace TomasAI.IFM.Domain.Trade.Order.Execution.Command.Actor;

public sealed class OrderExecutionCommandActor(ICommandActorContext<OrderExecutionCommandActor> context):BaseEventSourceCommandActor<OrderExecutionCommandActor>(context,Typed(context).Logger)
{
 public const string ActorName=OrderExecutionActorNames.Command;readonly IOrderExecutionCommandContext services=Typed(context);
 static readonly IReadOnlyDictionary<string,Func<IActorMessage,ICommand>> _parseMap=new Dictionary<string,Func<IActorMessage,ICommand>>(StringComparer.Ordinal){[StartOrderExecutionCommand.Verb]=m=>m.AsCommand<StartOrderExecutionCommand>()!,[SubmitOrderExecutionCommand.Verb]=m=>m.AsCommand<SubmitOrderExecutionCommand>()!,[AddOrderExecutionFillCommand.Verb]=m=>m.AsCommand<AddOrderExecutionFillCommand>()!,[AcceptOrderExecutionCommand.Verb]=m=>m.AsCommand<AcceptOrderExecutionCommand>()!,[CancelOrderExecutionCommand.Verb]=m=>m.AsCommand<CancelOrderExecutionCommand>()!,[RejectOrderExecutionCommand.Verb]=m=>m.AsCommand<RejectOrderExecutionCommand>()!}.ToFrozenDictionary(StringComparer.Ordinal);
 static readonly IReadOnlyDictionary<Type,Func<ICommand,List<ValidationError>>> _validationMap=new[]{typeof(StartOrderExecutionCommand),typeof(SubmitOrderExecutionCommand),typeof(AddOrderExecutionFillCommand),typeof(AcceptOrderExecutionCommand),typeof(CancelOrderExecutionCommand),typeof(RejectOrderExecutionCommand)}.ToDictionary(t=>t,_=>(Func<ICommand,List<ValidationError>>)Validate).ToFrozenDictionary();
 static readonly IReadOnlyDictionary<Type,Func<ICommand,OrderExecutionCommandState,ServiceResult<GuidResult>>> _receiveMap=new Dictionary<Type,Func<ICommand,OrderExecutionCommandState,ServiceResult<GuidResult>>>{[typeof(StartOrderExecutionCommand)]=static(c,s)=>((StartOrderExecutionCommand)c).Execute(s),[typeof(SubmitOrderExecutionCommand)]=static(c,s)=>((SubmitOrderExecutionCommand)c).Execute(s),[typeof(AddOrderExecutionFillCommand)]=static(c,s)=>((AddOrderExecutionFillCommand)c).Execute(s),[typeof(AcceptOrderExecutionCommand)]=static(c,s)=>((AcceptOrderExecutionCommand)c).Execute(s),[typeof(CancelOrderExecutionCommand)]=static(c,s)=>((CancelOrderExecutionCommand)c).Execute(s),[typeof(RejectOrderExecutionCommand)]=static(c,s)=>((RejectOrderExecutionCommand)c).Execute(s)}.ToFrozenDictionary();
 protected override ValueTask OnStartup(ICommandActorContext<OrderExecutionCommandActor> c)=>services.EventProjector.StartAsync(c);protected override ValueTask OnShutdown(ICommandActorContext<OrderExecutionCommandActor> c)=>services.EventProjector.StopAsync();protected override ICommand ParseMessage(ICommandActorContext<OrderExecutionCommandActor> c,IActorMessage m)=>ParseMappedCommand(c,m,_parseMap);protected override ValueTask OnValidateAsync(ICommandActorContext<OrderExecutionCommandActor> c,ActorThreadId id,ICommand command){ValidateMappedCommand(command,_validationMap);return ValueTask.CompletedTask;}protected override async ValueTask<IActorState> OnLoadStateAsync(ICommandActorContext<OrderExecutionCommandActor> c,ActorThreadId id,ICommand command)=>await services.StateRepository.LoadStateAsync(command);protected override async ValueTask OnSaveStateAsync(ICommandActorContext<OrderExecutionCommandActor> c,ActorThreadId id,IActorState state,ICommand command)=>await services.StateRepository.SaveStateAsync(c,(OrderExecutionCommandState)state,command);protected override ValueTask<ServiceResult<GuidResult>> ReceiveAsync(ICommandActorContext<OrderExecutionCommandActor> c,IActorState state,ICommand command)=>ValueTask.FromResult(ResolveMappedCommandHandler(command,_receiveMap)(command,(OrderExecutionCommandState)state));protected override ValueTask<ServiceResult<GuidResult>> OnExceptionAsync(ICommandActorContext<OrderExecutionCommandActor> c,ActorThreadId id,ICommand command,Exception ex)=>ValueTask.FromResult<ServiceResult<GuidResult>>(new ServiceFailed<GuidResult>(command.ErrorCode,ex.Message));
 static List<ValidationError> Validate(ICommand c)=>new List<ValidationError>().ValidateCommandId(c.CommandId,c.CommandName).CaptureCommandValidation(()=>{if(c is not ICommand<TomasAI.IFM.Domain.Trade.Shared.Model.OrderExecutionId> x||!x.EntityId.IsValid||c.Subject.EntityId!=x.EntityId.Format()||c is StartOrderExecutionCommand start&&(start.EntityId.TradeOrder!=start.Order.Id||start.EntityId.ExecutionAttemptId!=start.ExecutionAttemptId))throw new ArgumentException("Valid execution identity, matching order and attempt, and matching subject are required.");});static IOrderExecutionCommandContext Typed(ICommandActorContext<OrderExecutionCommandActor> c)=>c as IOrderExecutionCommandContext??throw new ArgumentException("Typed Order Execution context required.");
}
