ALTER ROLE [db_owner] ADD MEMBER [NT SERVICE\SQLAgent$DOMAINDATA];


GO
ALTER ROLE [db_accessadmin] ADD MEMBER [NT SERVICE\SQLAgent$DOMAINDATA];


GO
ALTER ROLE [db_securityadmin] ADD MEMBER [NT SERVICE\SQLAgent$DOMAINDATA];


GO
ALTER ROLE [db_ddladmin] ADD MEMBER [DEV-SERVER\IFMApp];


GO
ALTER ROLE [db_ddladmin] ADD MEMBER [NT SERVICE\SQLAgent$DOMAINDATA];


GO
ALTER ROLE [db_backupoperator] ADD MEMBER [NT SERVICE\SQLAgent$DOMAINDATA];


GO
ALTER ROLE [db_datareader] ADD MEMBER [NT SERVICE\SQLAgent$DOMAINDATA];


GO
ALTER ROLE [db_datawriter] ADD MEMBER [DEV-SERVER\IFMApp];


GO
ALTER ROLE [db_datawriter] ADD MEMBER [NT SERVICE\SQLAgent$DOMAINDATA];


GO
ALTER ROLE [db_denydatareader] ADD MEMBER [NT SERVICE\SQLAgent$DOMAINDATA];


GO
ALTER ROLE [db_denydatawriter] ADD MEMBER [NT SERVICE\SQLAgent$DOMAINDATA];

