CREATE TABLE [dbo].[trade_ticket] (
    [FundId]               INT           NOT NULL,
    [OrderId]              INT           NOT NULL,
    [TradeId]              INT           NOT NULL,
    [ValueDate]            DATETIME      NOT NULL,
    [TradeType]            VARCHAR (32)  NOT NULL,
    [TradeSubType]         VARCHAR (32)  NULL,
    [TradeDate]            DATE          NOT NULL,
    [MaturityDate]         DATE          NOT NULL,
    [TradeState]           VARCHAR (32)  NOT NULL,
    [UnderlyingContractId] VARCHAR (64)  NULL,
    [UnderlyingAssetType]  VARCHAR (32)  NULL,
    [OrderDescription]     VARCHAR (256) NULL,
    [OrderAction]          VARCHAR (32)  NOT NULL,
    [OrderActionType]      VARCHAR (32)  NOT NULL,
    [OrderQuantity]        INT           NOT NULL,
    [OrderType]            VARCHAR (32)  NOT NULL,
    [OrderPrice]           MONEY         NOT NULL,
    [OrderAmount]          MONEY         NOT NULL,
    [Commission]           MONEY         NOT NULL,
    [TotalAmount]          MONEY         NOT NULL,
    [TradePnl]             MONEY         NOT NULL,
    [TradeFillType]        VARCHAR (32)  NULL,
    [CreatedOn]            DATETIME      NULL,
    [CreatedBy]            VARCHAR (64)  NULL,
    [UpdatedOn]            DATETIME      NULL,
    [UpdatedBy]            VARCHAR (64)  NULL,
    CONSTRAINT [PK_trade_ticket_1] PRIMARY KEY CLUSTERED ([FundId] ASC, [OrderId] ASC, [TradeId] ASC)
);

