using TomasAI.IFM.Domain.Portfolio.FinancialPolicy.Command.Model;
using TomasAI.IFM.Domain.Portfolio.Fund.Command.Model;
using TomasAI.IFM.Domain.Portfolio.Shared.Events;
using TomasAI.IFM.Domain.Portfolio.Shared.Fund.Events;
using TomasAI.IFM.Domain.Portfolio.Shared.FinancialPolicy.Events;
namespace TomasAI.IFM.Domain.Portfolio.Command.Model;

/// <summary>Preserves aggregate-call compatibility; mapped handlers own their explicit event factories.</summary>
internal static class PortfolioComputedEvents
{
    internal static IPortfolioDomainEvent Create(IPortfolioChange change) => change switch
    {
        PortfolioRetiredCompute businessChange => new PortfolioRetiredEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, Reason = businessChange.Reason },
        PortfolioCreatedCompute businessChange => new PortfolioCreatedEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, Portfolio = businessChange.PortfolioDefinition, IdempotencyKey = businessChange.IdempotencyKey },
        PortfolioFinancialPolicyAssignedCompute businessChange => new PortfolioFinancialPolicyAssignedEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, PolicyId = businessChange.PolicyId, PolicyVersion = businessChange.PolicyVersion },
        FundAllocationDelegatedCompute businessChange => new FundAllocationDelegatedEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, Allocation = businessChange.FundAllocation },
        FundAddedToPortfolioCompute businessChange => new FundAddedToPortfolioEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, FundId = businessChange.FundId },
        DraftPortfolioDeletedCompute businessChange => new DraftPortfolioDeletedEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, Reason = businessChange.Reason },
        PortfolioOperatingStateChangedCompute businessChange => new PortfolioOperatingStateChangedEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, State = businessChange.OperatingState, Reason = businessChange.Reason },
        PortfolioVersionAddedCompute businessChange => new PortfolioVersionAddedEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, Portfolio = businessChange.PortfolioDefinition },
        FundRiskEnvelopeDelegatedCompute businessChange => new FundRiskEnvelopeDelegatedEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, Envelope = businessChange.FundRiskEnvelope },
        _ => throw new ArgumentOutOfRangeException(nameof(change))
    };
    internal static IPortfolioFundDomainEvent Create(IPortfolioFundChange change) => change switch
    {
        FundManualOrderDeletedCompute businessChange => new FundManualOrderDeletedEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, OrderId = businessChange.OrderId, RemovedTradeIds = businessChange.RemovedTradeIds },
        FundCompositionStateChangedCompute businessChange => new FundCompositionStateChangedEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, Order = businessChange.FundOrder },
        FundTradeTemplateAssignedCompute businessChange => new FundTradeTemplateAssignedEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, Assignment = businessChange.TradeTemplateAssignment },
        FundManualOrderChangedCompute businessChange => new FundManualOrderChangedEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, Reservation = businessChange.FundCompositionReservation, RemovedTradeId = businessChange.RemovedTradeId },
        FundMandateCreatedCompute businessChange => new FundMandateCreatedEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, Mandate = businessChange.FundMandate, IdempotencyKey = businessChange.IdempotencyKey },
        FundOperatingStateChangedCompute businessChange => new FundOperatingStateChangedEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, State = businessChange.OperatingState, Reason = businessChange.Reason },
        FundMandateVersionAddedCompute businessChange => new FundMandateVersionAddedEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, Mandate = businessChange.FundMandate },
        FundCompositionReservedCompute businessChange => new FundCompositionReservedEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, Reservation = businessChange.FundCompositionReservation },
        _ => throw new ArgumentOutOfRangeException(nameof(change))
    };
    internal static IPortfolioFinancialPolicyDomainEvent Create(IPortfolioFinancialPolicyChange change) => change switch
    {
        PortfolioFinancialPolicyRetiredCompute businessChange => new PortfolioFinancialPolicyRetiredEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, PolicyVersion = businessChange.PolicyVersion, Reason = businessChange.Reason },
        PortfolioFinancialPolicyActivatedCompute businessChange => new PortfolioFinancialPolicyActivatedEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, PolicyVersion = businessChange.PolicyVersion },
        PortfolioFinancialPolicyCreatedCompute businessChange => new PortfolioFinancialPolicyCreatedEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, Policy = businessChange.FinancialPolicy, IdempotencyKey = businessChange.IdempotencyKey },
        DraftPortfolioFinancialPolicyDeletedCompute businessChange => new DraftPortfolioFinancialPolicyDeletedEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, Reason = businessChange.Reason },
        PortfolioFinancialPolicyVersionAddedCompute businessChange => new PortfolioFinancialPolicyVersionAddedEvent { Id = businessChange.Id, CommandId = businessChange.CommandId, Revision = businessChange.Revision, OccurredOnUtc = businessChange.OccurredOnUtc, ReceivedOn = businessChange.OccurredOnUtc, OriginatedOnUtc = businessChange.OccurredOnUtc, Principal = businessChange.Principal, Policy = businessChange.FinancialPolicy },
        _ => throw new ArgumentOutOfRangeException(nameof(change))
    };
}
