name: natsjetstream

services:
  nats:
    image: nats:2.12.0-alpine
    container_name: ifm-nats-server
    command: [ "-js", "-sd", "/data", "-p", "4222", "-m", "8222" ]
    ports:
      - "4222:4222"
      - "127.0.0.1:8222:8222"
    volumes:
      - nats-data:/data
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--spider", "http://127.0.0.1:8222/healthz" ]
      interval: 10s
      timeout: 3s
      start_period: 10s
      retries: 6

volumes:
  nats-data:
    external: true
    name: natsjetstream_nats_data
