**

!Directory.Build.props
!Directory.Packages.props
!global.json

!TomasAI.IFM.Api.DatabaseBackup.Host/
!TomasAI.IFM.Api.DatabaseBackup.Host/**
!TomasAI.IFM.Application.DatabaseBackup/
!TomasAI.IFM.Application.DatabaseBackup/**
!TomasAI.IFM.Domain.SystemAdmin.Shared/
!TomasAI.IFM.Domain.SystemAdmin.Shared/**
!TomasAI.IFM.Framework.Messaging.Nats/
!TomasAI.IFM.Framework.Messaging.Nats/**
!TomasAI.IFM.Framework.Serialization/
!TomasAI.IFM.Framework.Serialization/**
!TomasAI.IFM.Framework.Storage.DatabaseBackup.LocalWorkstation/
!TomasAI.IFM.Framework.Storage.DatabaseBackup.LocalWorkstation/**
!TomasAI.IFM.Framework.Storage.DatabaseBackup.AwsCloud/
!TomasAI.IFM.Framework.Storage.DatabaseBackup.AwsCloud/**
!TomasAI.IFM.Shared/
!TomasAI.IFM.Shared/**


# Shared contract dependencies used by scheduled market tasks.
!TomasAI.IFM.Domain.MarketData.Analytics.Shared/
!TomasAI.IFM.Domain.MarketData.Analytics.Shared/**
!TomasAI.IFM.Domain.MarketData.Shared/
!TomasAI.IFM.Domain.MarketData.Shared/**
!TomasAI.IFM.Domain.Portfolio.Shared/
!TomasAI.IFM.Domain.Portfolio.Shared/**
!TomasAI.IFM.Domain.Strategy.Contracts.Shared/
!TomasAI.IFM.Domain.Strategy.Contracts.Shared/**
!TomasAI.IFM.Domain.Trade.Shared/
!TomasAI.IFM.Domain.Trade.Shared/**

**/bin/
**/obj/
**/.git/

**/.artifacts/
**/TestResults/
