using System;
using System.Collections.Generic;
using System.Text;

namespace TomasAI.IFM.Shared.Trade
{
    public enum ActionSubType
    {
        Error,
        None,
        OrderPartiallyFilled,
        OrderFilled,
        FillOrderWait,
        TradeInProfitPosition,
        TradeInLossPosition,
        InTrailingStop,
        RaiseTrailingStopLimit,
        TrailingStopLimitReached,
        MinProfitTargetExceeded,
        MinStopLossLimitReached,
        MaxLossLimitReached,
        PutSpreadAtRisk,
        CallSpreadAtRisk,
        ClearStopLossLimit,
        ForwardLossRiskLimitReached,
        MediumRisk,
        MinProfitLimitReached,
        HighShortCallGammaRisk,
        LowShortCallGammaRisk,
        HighShortPutGammaRisk,
        LowShortPutGammaRisk,
        MarketPositionChanged,
        MaxLossRiskLimitReached,
        WarningLossLimitReached,
        CriticalLossLimitReached,
        MaxAssetPriceChangeDownReached,
        MarketNotTrendingUp,
        MarketNotTrendingDown,
        MarketNotTrendingUpWarning,
        MarketNotTrendingDownWarning,
        MarketNotTrendingUpLimitExceeded,
        MarketNotTrendingDownLimitExceeded,
        ForwardLossRiskLimitWarning,
        ForwardLossRiskLimitClear,
        MarketRevertingToDownTrend,
        MarketRevertingToUpTrend,
        DailyProfitTargetExceeded,
        ForwardLossRiskLimitReachedWarning,
        MinTrailingStopLimitReached,
        MarketInUpTrend,
        MarketInDownTrend,
        MDIWatermarkLimitReached,
        MarketDownTrending,
        MarketUpTrending,
    }

    public static class ActionSubTypeExtensions
    {
        public static string ToStringFast(this ActionSubType value) => value switch
        {
            ActionSubType.Error => nameof(ActionSubType.Error),
            ActionSubType.None => nameof(ActionSubType.None),
            ActionSubType.OrderPartiallyFilled => nameof(ActionSubType.OrderPartiallyFilled),
            ActionSubType.OrderFilled => nameof(ActionSubType.OrderFilled),
            ActionSubType.FillOrderWait => nameof(ActionSubType.FillOrderWait),
            ActionSubType.TradeInProfitPosition => nameof(ActionSubType.TradeInProfitPosition),
            ActionSubType.TradeInLossPosition => nameof(ActionSubType.TradeInLossPosition),
            ActionSubType.InTrailingStop => nameof(ActionSubType.InTrailingStop),
            ActionSubType.RaiseTrailingStopLimit => nameof(ActionSubType.RaiseTrailingStopLimit),
            ActionSubType.TrailingStopLimitReached => nameof(ActionSubType.TrailingStopLimitReached),
            ActionSubType.MinProfitTargetExceeded => nameof(ActionSubType.MinProfitTargetExceeded),
            ActionSubType.MinStopLossLimitReached => nameof(ActionSubType.MinStopLossLimitReached),
            ActionSubType.MaxLossLimitReached => nameof(ActionSubType.MaxLossLimitReached),
            ActionSubType.PutSpreadAtRisk => nameof(ActionSubType.PutSpreadAtRisk),
            ActionSubType.CallSpreadAtRisk => nameof(ActionSubType.CallSpreadAtRisk),
            ActionSubType.ClearStopLossLimit => nameof(ActionSubType.ClearStopLossLimit),
            ActionSubType.ForwardLossRiskLimitReached => nameof(ActionSubType.ForwardLossRiskLimitReached),
            ActionSubType.MediumRisk => nameof(ActionSubType.MediumRisk),
            ActionSubType.MinProfitLimitReached => nameof(ActionSubType.MinProfitLimitReached),
            ActionSubType.HighShortCallGammaRisk => nameof(ActionSubType.HighShortCallGammaRisk),
            ActionSubType.LowShortCallGammaRisk => nameof(ActionSubType.LowShortCallGammaRisk),
            ActionSubType.HighShortPutGammaRisk => nameof(ActionSubType.HighShortPutGammaRisk),
            ActionSubType.LowShortPutGammaRisk => nameof(ActionSubType.LowShortPutGammaRisk),
            ActionSubType.MarketPositionChanged => nameof(ActionSubType.MarketPositionChanged),
            ActionSubType.MaxLossRiskLimitReached => nameof(ActionSubType.MaxLossRiskLimitReached),
            ActionSubType.WarningLossLimitReached => nameof(ActionSubType.WarningLossLimitReached),
            ActionSubType.CriticalLossLimitReached => nameof(ActionSubType.CriticalLossLimitReached),
            ActionSubType.MaxAssetPriceChangeDownReached => nameof(ActionSubType.MaxAssetPriceChangeDownReached),
            ActionSubType.MarketNotTrendingUp => nameof(ActionSubType.MarketNotTrendingUp),
            ActionSubType.MarketNotTrendingDown => nameof(ActionSubType.MarketNotTrendingDown),
            ActionSubType.MarketNotTrendingUpWarning => nameof(ActionSubType.MarketNotTrendingUpWarning),
            ActionSubType.MarketNotTrendingDownWarning => nameof(ActionSubType.MarketNotTrendingDownWarning),
            ActionSubType.MarketNotTrendingUpLimitExceeded => nameof(ActionSubType.MarketNotTrendingUpLimitExceeded),
            ActionSubType.MarketNotTrendingDownLimitExceeded => nameof(ActionSubType.MarketNotTrendingDownLimitExceeded),
            ActionSubType.ForwardLossRiskLimitWarning => nameof(ActionSubType.ForwardLossRiskLimitWarning),
            ActionSubType.ForwardLossRiskLimitClear => nameof(ActionSubType.ForwardLossRiskLimitClear),
            ActionSubType.MarketRevertingToDownTrend => nameof(ActionSubType.MarketRevertingToDownTrend),
            ActionSubType.MarketRevertingToUpTrend => nameof(ActionSubType.MarketRevertingToUpTrend),
            ActionSubType.DailyProfitTargetExceeded => nameof(ActionSubType.DailyProfitTargetExceeded),
            ActionSubType.ForwardLossRiskLimitReachedWarning => nameof(ActionSubType.ForwardLossRiskLimitReachedWarning),
            ActionSubType.MinTrailingStopLimitReached => nameof(ActionSubType.MinTrailingStopLimitReached),
            ActionSubType.MarketInUpTrend => nameof(ActionSubType.MarketInUpTrend),
            ActionSubType.MarketInDownTrend => nameof(ActionSubType.MarketInDownTrend),
            ActionSubType.MDIWatermarkLimitReached => nameof(ActionSubType.MDIWatermarkLimitReached),
            ActionSubType.MarketDownTrending => nameof(ActionSubType.MarketDownTrending),
            ActionSubType.MarketUpTrending => nameof(ActionSubType.MarketUpTrending),
            _ => value.ToString()
        };
    }
}
