namespace TomasAI.IFM.Shared.EventSourcing;

/// <summary>
/// aggregate names
/// </summary>
public enum BoundedContextName
{
    Undefined,
    EconomicCalendarBoundedContext,
    FundBoundedContext,
    FundTransactionBoundedContext,
    FuturesContractBoundedContext,
    FuturesOptionContractBoundedContext,
    YieldCurveRateBoundedContext,
    FuturesBarDataBoundedContext,
    FuturesTickDataBoundedContext,
    FuturesEodDataBoundedContext,
    FuturesOptionTickDataBoundedContext,
    SpreadDistributionBoundedContext,
    OptionTradeBoundedContext,
    TradePlanBoundedContext,
    SpreadDistributionJobBoundedContext,
    LookupTypeBoundedContext,
    SystemAdminBoundedContext,
    MarketDataFeedBoundedContext,
    TradeOrderBoundedContext,
    StrikePriceVolatilityBoundedContext,
    FuturesClosingPriceBoundedContext,
    ApplicationBoundedContext,
    FuturesTradeSignalBoundedContext,
    IronCondorTradeAlgorithmBoundedContext,
    TradePlanForwardLossLimitBoundedContext,
    TradePlacementBoundedContext,
    FuturesRsiSignalBoundedContext,
    FuturesTdiSignalBoundedContext,
    FuturesTradeSignalLLMBoundedContext,
    TelemetryLogsBoundedContext,
    FuturesItiSignalBoundedContext,
    FuturesItiTrendBoundedContext,
    FuturesOptionQuoteDataBoundedContext,
    TradeAlgorithmBoundedContext,
    FuturesMacdSignalBoundedContext,
    FuturesAtrSignalBoundedContext,
    FuturesAdxSignalBoundedContext,
}

public static class BoundedContextNameExtensions
{
    public static string ToStringFast(this BoundedContextName value) => value switch
    {
        BoundedContextName.Undefined => nameof(BoundedContextName.Undefined),
        BoundedContextName.EconomicCalendarBoundedContext => nameof(BoundedContextName.EconomicCalendarBoundedContext),
        BoundedContextName.FundBoundedContext => nameof(BoundedContextName.FundBoundedContext),
        BoundedContextName.FundTransactionBoundedContext => nameof(BoundedContextName.FundTransactionBoundedContext),
        BoundedContextName.FuturesContractBoundedContext => nameof(BoundedContextName.FuturesContractBoundedContext),
        BoundedContextName.FuturesOptionContractBoundedContext => nameof(BoundedContextName.FuturesOptionContractBoundedContext),
        BoundedContextName.YieldCurveRateBoundedContext => nameof(BoundedContextName.YieldCurveRateBoundedContext),
        BoundedContextName.FuturesBarDataBoundedContext => nameof(BoundedContextName.FuturesBarDataBoundedContext),
        BoundedContextName.FuturesTickDataBoundedContext => nameof(BoundedContextName.FuturesTickDataBoundedContext),
        BoundedContextName.FuturesEodDataBoundedContext => nameof(BoundedContextName.FuturesEodDataBoundedContext),
        BoundedContextName.FuturesOptionTickDataBoundedContext => nameof(BoundedContextName.FuturesOptionTickDataBoundedContext),
        BoundedContextName.SpreadDistributionBoundedContext => nameof(BoundedContextName.SpreadDistributionBoundedContext),
        BoundedContextName.OptionTradeBoundedContext => nameof(BoundedContextName.OptionTradeBoundedContext),
        BoundedContextName.TradePlanBoundedContext => nameof(BoundedContextName.TradePlanBoundedContext),
        BoundedContextName.SpreadDistributionJobBoundedContext => nameof(BoundedContextName.SpreadDistributionJobBoundedContext),
        BoundedContextName.LookupTypeBoundedContext => nameof(BoundedContextName.LookupTypeBoundedContext),
        BoundedContextName.SystemAdminBoundedContext => nameof(BoundedContextName.SystemAdminBoundedContext),
        BoundedContextName.MarketDataFeedBoundedContext => nameof(BoundedContextName.MarketDataFeedBoundedContext),
        BoundedContextName.TradeOrderBoundedContext => nameof(BoundedContextName.TradeOrderBoundedContext),
        BoundedContextName.StrikePriceVolatilityBoundedContext => nameof(BoundedContextName.StrikePriceVolatilityBoundedContext),
        BoundedContextName.FuturesClosingPriceBoundedContext => nameof(BoundedContextName.FuturesClosingPriceBoundedContext),
        BoundedContextName.ApplicationBoundedContext => nameof(BoundedContextName.ApplicationBoundedContext),
        BoundedContextName.FuturesTradeSignalBoundedContext => nameof(BoundedContextName.FuturesTradeSignalBoundedContext),
        BoundedContextName.IronCondorTradeAlgorithmBoundedContext => nameof(BoundedContextName.IronCondorTradeAlgorithmBoundedContext),
        BoundedContextName.TradePlanForwardLossLimitBoundedContext => nameof(BoundedContextName.TradePlanForwardLossLimitBoundedContext),
        BoundedContextName.TradePlacementBoundedContext => nameof(BoundedContextName.TradePlacementBoundedContext),
        BoundedContextName.FuturesRsiSignalBoundedContext => nameof(BoundedContextName.FuturesRsiSignalBoundedContext),
        BoundedContextName.FuturesTdiSignalBoundedContext => nameof(BoundedContextName.FuturesTdiSignalBoundedContext),
        BoundedContextName.FuturesTradeSignalLLMBoundedContext => nameof(BoundedContextName.FuturesTradeSignalLLMBoundedContext),
        BoundedContextName.TelemetryLogsBoundedContext => nameof(BoundedContextName.TelemetryLogsBoundedContext),
        BoundedContextName.FuturesItiSignalBoundedContext => nameof(BoundedContextName.FuturesItiSignalBoundedContext),
        BoundedContextName.FuturesItiTrendBoundedContext => nameof(BoundedContextName.FuturesItiTrendBoundedContext),
        BoundedContextName.FuturesOptionQuoteDataBoundedContext => nameof(BoundedContextName.FuturesOptionQuoteDataBoundedContext),
        BoundedContextName.TradeAlgorithmBoundedContext => nameof(BoundedContextName.TradeAlgorithmBoundedContext),
        BoundedContextName.FuturesMacdSignalBoundedContext => nameof(BoundedContextName.FuturesMacdSignalBoundedContext),
        BoundedContextName.FuturesAtrSignalBoundedContext => nameof(BoundedContextName.FuturesAtrSignalBoundedContext),
        BoundedContextName.FuturesAdxSignalBoundedContext => nameof(BoundedContextName.FuturesAdxSignalBoundedContext),
        _ => value.ToString()
    };
}
