<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TomasAI.IFM.Domain.MarketData.Analytics.Actor.BDDTests" />
    <InternalsVisibleTo Include="TomasAI.IFM.Domain.MarketData.Analytics.Actor.UnitTests" />
    <InternalsVisibleTo Include="TomasAI.IFM.Domain.MarketData.Analytics.UnitTests" />
    <InternalsVisibleTo Include="TomasAI.IFM.Domain.MarketData.Analytics.IntegrationTests" />
    <InternalsVisibleTo Include="TomasAI.IFM.Domain.MarketData.Analytics.Benchmarks" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TomasAI.IFM.Application.EventProjector\TomasAI.IFM.Application.EventProjector.csproj" />
    <ProjectReference Include="..\TomasAI.IFM.Application.MarketData\TomasAI.IFM.Application.MarketData.csproj" />
    <ProjectReference Include="..\TomasAI.IFM.Application.Storage\TomasAI.IFM.Application.Storage.csproj" />
    <ProjectReference Include="..\TomasAI.IFM.Shared.Domain\TomasAI.IFM.Shared.Domain.csproj" />
    <ProjectReference Include="..\TomasAI.IFM.Shared\TomasAI.IFM.Shared.csproj" />
    <ProjectReference Include="..\TomasAI.IFM.Domain.MarketData.Analytics.Shared\TomasAI.IFM.Domain.MarketData.Analytics.Shared.csproj" />
    <ProjectReference Include="..\TomasAI.IFM.Domain.PredictiveModel.Shared\TomasAI.IFM.Domain.PredictiveModel.Shared.csproj" />
    <ProjectReference Include="..\TomasAI.IFM.Domain.MarketData.Feed.Shared\TomasAI.IFM.Domain.MarketData.Feed.Shared.csproj" />
      <ProjectReference Include="..\TomasAI.IFM.Domain.Trade.Shared\TomasAI.IFM.Domain.Trade.Shared.csproj" />
      <ProjectReference Include="..\TomasAI.IFM.Domain.MarketData.Shared\TomasAI.IFM.Domain.MarketData.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="MarketEvaluationSnapshot\" />
    <Folder Include="VixVolatility\Command\" />
    <Folder Include="VixVolatility\Event\" />
    <Folder Include="VixVolatility\Query\" />
  </ItemGroup>

</Project>
