#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 23429
EXPOSE 23430

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Directory.Build.props", "."]
COPY ["TomasAI.IFM.Application.Telemetry.Server/TomasAI.IFM.Application.Telemetry.Server.csproj", "TomasAI.IFM.Application.Telemetry.Server/"]
RUN dotnet restore "TomasAI.IFM.Application.Telemetry.Server/TomasAI.IFM.Application.Telemetry.Server.csproj"
COPY . .
WORKDIR "/src/TomasAI.IFM.Application.Telemetry.Server"
RUN dotnet build "TomasAI.IFM.Application.Telemetry.Server.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TomasAI.IFM.Application.Telemetry.Server.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TomasAI.IFM.Application.Telemetry.Server.dll"]